### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/rudyard-kipling_just-so-stories#4]
- In long description, use double quotes around text like "origin" and "just so"
- Since Kipling is also the illustrator, it is enough to add an additional `<meta property="role" refines="#author" scheme="marc:relators">ill</meta>` tag to his exiting info block, without duplicating his name/wiki/nacoaf information again.
- `transcriber-1` has the role of `ann` but there are no endnotes?

**Comment by drgrigg** [comment]
There were originally notes from the transcriber about the variant spellings Kipling used, and I also added a note. But we agreed (on the forum) that they weren't necessary.
