### ISSUE TITLE
Illustration semantics

### ISSUE THREAD

**Issue by acabal** [drgrigg/rudyard-kipling_just-so-stories#5]
For the illustrations, I'm looking at the whale images in How the Whale got his Throat to start out with. Notes:

- You used a `div` with the `z3998:figure` semantic, but that's what the `<figure>` element is for. Additionally you used `<p>` tags for the captions, but we have the `<figcaption>` element for that. See https://standardebooks.org/contribute/semantics#images for a markup example.
- I also see that the figure is part of the poem `<blockquote>`.  I think it should be pulled out of that as it is not a quotation, but rather part of the story. It can go directly after the `<blockquote>` instead of being a child.
- The `alt` tags do not really describe the images in words, for screen readers. For example the `alt` attribute of "The Whale swallowing the Mariner with his infinite-resource-and-sagacity." doesn't really describe the picture. How does the picture convey "infinite resources and sagacity?" A more accurate/factual description might be "A massive whale is breaching the water. His mouth is open around a mariner in the water, and the whale is preparing to swallow."  `alt` is for screen readers, so it should be a textual description of the illustration so that the visually impaired can visualize the drawing itself. `<figcaption>` is the longer description that can be more detailed or fuzzy in terms of description.

    The next image might be tougher to describe in `alt` since it's more abstract, but maybe something like "A whale looks down on a fish. The fish is hidden under horizontal doorsills, and covered by an abstract structure like tree roots." (I haven't read the story so maybe there's a better way to describe that illustration.)
- For the illustration filenames and their IDs, please use the full word: `illustration-01-01` and not `illo-01-01`.

I don't know if these issues are common through the entire production, I haven't looked yet, but please review the rest and update them if necessary.

**Comment by acabal** [comment]
Also, for filenames, don't use leading 0s, just like we wouldn't use leading 0s in chapter numbers in filenames.

**Comment by acabal** [comment]
Also, per the semantics manual, put the ID attribute on the parent `<figure>` tag, not on the `<img>` tag within the figure. (Once you update them to replace the `<div>`s.)

**Comment by acabal** [comment]
I also see that the figures are meant to be full-page illustrations, since they have the `page-break-before` style. In that case, remove the `<hr>` before the figure, since the page should break there anyway. Once you update to the correct `<figure>` semantics, make sure to update the CSS to match, since it looks like the CSS is not complete in terms of what the standards require.

**Comment by drgrigg** [comment]
I'm not sure how to handle the fact that there are two distinct types of figure: the full-page illustrations and those inline. The CSS examples in the Semantics Manual seem to assume that only one kind of figure is going to be included in a production. Obviously we don't want a page break before each alphabet character! If I make them all figures, how do I differentiate between them in the CSS without using classes? After my experience with "Enchanted Castle" I must say I'm tempted to make all the images inline...

**Comment by acabal** [comment]
Hmm... that's a good point, I think until now we've always had either all-inline or all-full-page cases. 

I think we more often have inline illustrations than full-page ones. So, why don't we update the standard so that `figure.full-page` is how we target full-page illustrations. So in the manual's example, you would update only the first selector to `figure.full-page` and then add the `full-page` class to those figure elements in the markup. How does that sound?

**Comment by drgrigg** [comment]
Done!
