### ISSUE TITLE
alphabet class

### ISSUE THREAD

**Issue by acabal** [drgrigg/rudyard-kipling_just-so-stories#7]
The `alphabet` class has some redundant styling. Really all you need for it is the max-height and max-width. The other styles in that class, including margins, are applied by the figure standards. You can open the file in Firefox and use the inspector to confirm which styles cascade down from others, so we don't repeat ourselves in the CSS.

Also pleases use percentages in max-height and max-width; I know vw/vh are more convenient/accurate but I'm pretty sure there's little to no reading system support for those values at the moment.  (There's a lot of CSS we can't really use that would be nice, like Flexbox for vertical centering on a page...)

**Comment by acabal** [comment]
Same for the "letter" class.

**Comment by drgrigg** [comment]
Done
