### ISSUE TITLE
Put source images in the ./images/ folder

### ISSUE THREAD

**Issue by acabal** [drgrigg/rudyard-kipling_just-so-stories#8]
Since you converted all the images in the book to SVG, we want to keep the source images (jpg/png/whatever) around in case we want to do other things to them in the future. You can keep those in the `./images/` folder along with the cover source image and the rest of that stuff.

Make sure to store the highest resolution images possible, in a lossless format like PNG if possible.

**Comment by drgrigg** [comment]
Done. I've included the source files for the dropcap images, even though at present I'm not proposing to include them in the book, just in case some future producer decides otherwise. All image files have been renumbered and renamed (and of course all references to them updated in the xhtml files)

**Comment by acabal** [comment]
If you removed the dropcap svgs, can you maybe dig them out of the Git history and put them in `./images/` too, in case we use them in the future?

**Comment by drgrigg** [comment]
Done. But I'm not going to think up descriptive alt tags for them. The future producer can do that!

**Comment by acabal** [comment]
Heh OK. To be clear I mean the `<ebook-root>/images/` folder, not `<ebook-root>/src/epub/images/` for all of these.

**Comment by drgrigg** [comment]
Understood.
